server:
  port: 8020
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/spcloud-proj-demo-01?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    username: ale
    password: a123456
    driver-class-name: com.mysql.cj.jdbc.Driver
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
mybatis:
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: com.ale.bean  
